server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启动态路由
      routes:
        - id: payment_routh          # 路由的 id,没有固定规则,但要求唯一,建议配合服务名
#          http://localhost:8001
          uri:  lb://CLOUD-PAYMENT-SERVICE # 动态路由
          predicates:
            - Path=/payment/get/**   # 断言,路径相匹配的进行路由

        - id: payment_routh2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
#            - Cookie=username,zzyy


eureka:
  instance:
    hostname: cloud-gateway-service

  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.test:7001/eureka,http://eureka7002.test:7002/eureka
