server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
          group: mofeng
      binders:
        defaultRabbit:
          type: rabbit


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.test:7001/eureka,http://eureka7002.test:7002/eureka
  instance:
    lease-renewal-interval-in-seconds: 30
    instance-id: receive-8803.test
    prefer-ip-address: true

